version: '2'
services:
    httpsessionauthdemo-app:
        image: httpsessionauthdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://httpsessionauthdemo-mysql:3306/httpsessionauthdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    httpsessionauthdemo-mysql:
        extends:
            file: mysql.yml
            service: httpsessionauthdemo-mysql
